[package]
name = "zinzen_scheduler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']
name = 'scheduler'

[profile.release]
opt-level = 3
lto = true

[dependencies]
serde_json = "1.0.81"
serde = { version = "*", features = ["derive"] }
time = { version = "0.3.9", features = ["serde"] }
linked-list = "0.0.3"
