[package]
name = "zinzen"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
keywords = ["zinzen", "scheduler", "todo"]
description = "Algorithm for auto-scheduling time-constrained tasks on a calendar"
homepage = "https://github.com/tijlleenders/ZinZen-scheduler/wiki"
repository = "https://github.com/tijlleenders/ZinZen-scheduler"
readme = "README.md"
categories = ["algorithms","date-and-time","wasm"]

[lib]
crate-type = ['cdylib']
name = 'scheduler'

[profile.release]
opt-level = 3
lto = true

[dependencies]
serde_json = "1.0.81"
serde = { version = "*", features = ["derive"] }
time = { version = "0.3.9", features = ["serde"] }
linked-list = "0.0.3"
