[package]
name = "zinzen"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
keywords = ["zinzen", "scheduler", "todo"]
description = "Algorithm for auto-scheduling time-constrained tasks on a timeline"
homepage = "https://github.com/tijlleenders/ZinZen-scheduler/wiki"
repository = "https://github.com/tijlleenders/ZinZen-scheduler"
readme = "README.md"
categories = ["algorithms", "date-and-time", "wasm"]

[lib]
crate-type = ['cdylib']
name = 'scheduler'

[profile.release]
lto = true
# Tell `rustc` to optimize for small code size.
opt-level = "s"


[dependencies]
serde_json = "1.0.82"
serde = { version = "1.0.139", features = ["derive"] }
chrono = { version = "0.4.19", features = ["wasmbind", "serde"] }
linked-list = "0.0.3"
anyhow = "1.0.58"

# simple WASM codegen
wasm-bindgen = { version = "0.2.81", features = ["serde-serialize"] }

# display Rust panics as console.error()
console_error_panic_hook = "0.1.7"
